Arben
WSU-4110/SafeFoodie pull request #71
Opened 2022-12-01 22:02 UTC by AlfieCakez

2022-12-04 03:00 UTC, savvyp requested changes

2022-12-04 03:00 UTC, savvyp commented on SafeFoodie_Fresh/lib/screens/add_to_list.dart
> +void main() {
Please add brief comments for understanding, but otherwise looks good!

2022-12-04 03:00 UTC, savvyp commented on SafeFoodie_Fresh/lib/screens/home/CreateNew.dart
> +                  child: new Text(title,
no need to make this into new keywords, you're good to remove "new" from the front of this

2022-12-04 03:00 UTC, savvyp commented on SafeFoodie_Fresh/lib/screens/home/CreateNew.dart
> +                          new TextStyle(fontSize: 18.0, color: Colors.white)),
no need to make this into new keywords, you're good to remove "new" from the front of this

2022-12-04 03:00 UTC, savvyp commented on SafeFoodie_Fresh/lib/screens/home/CreateNew.dart
> +          child: new InkWell(
no need to make this into new keywords, you're good to remove "new" from the front of this

2022-12-04 03:00 UTC, savvyp commented on SafeFoodie_Fresh/lib/screens/newlist.dart
> +    return new Scaffold(
no need to make this into new keywords, you're good to remove "new" from the front of this. Also for AppBar, Text, Column, TextField, etc.

2022-12-04 03:00 UTC, savvyp commented on SafeFoodie_Fresh/lib/screens/newlist.dart
> +//Center action button
This looks great!!

2022-12-07 03:28 UTC, closed without merging

2022-12-07 21:03 UTC, Arbanzo commented on SafeFoodie_Fresh/lib/screens/add_to_list.dart
> +void main() {
It was fixed!

2022-12-08 04:54 UTC, AlfieCakez commented on SafeFoodie_Fresh/lib/screens/home/CreateNew.dart
> +                  child: new Text(title,
We removed

2022-12-08 04:55 UTC, AlfieCakez commented on SafeFoodie_Fresh/lib/screens/home/CreateNew.dart
> +          child: new InkWell(
Removed this redundancy

2022-12-08 04:55 UTC, AlfieCakez commented on SafeFoodie_Fresh/lib/screens/newlist.dart
> +//Center action button
thanks :)